# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
#uncomment this to see lab task before "Connect multiple virtual machines with VPN"
#     config.vm.box = BOX_IMAGE
#     config.vm.provision :shell, path: "bootstrap.sh"
#     config.vm.network :forwarded_port, guest: 80, host: 4567

#comment this to see lab task before "Connect multiple virtual machines with VPN"
    config.vm.define "master" do |subconfig|
        subconfig.vm.hostname = "master"
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.network :private_network, ip: "10.0.0.10"
#         config.vm.provision :shell, path: "bootstrap.sh"
#         config.vm.network :forwarded_port, guest: 80, host: 4567
      end

      config.vm.define "node1" do |subconfig|
        subconfig.vm.hostname = "node1"
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.network :private_network, ip: "10.0.0.11"
      end

      config.vm.define "node2" do |subconfig|
        subconfig.vm.hostname = "node2"
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.network :private_network, ip: "10.0.0.12"
      end
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update && apt-get install -y avahi-daemon libnss-mdns
  SHELL
end
